### PR TITLE
Updates Danger-Swift

### PR DESCRIPTION
**Pull request by ashfurrow**
This is a PR (not to master) to test whether upgrading Danger-Swift fixes a CI failure we saw this week. The failure was caused by commits in the PR that weren't from normal GitHub user accounts, but rather, were from bots. See: https://github.com/danger/swift/issues/281#issuecomment-538299682

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  danger-swift` failed.
  </td>
    </tr>
  </tbody>
</table>



### Log


```sh
/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/_tmp_dangerfile.swift:30:47: error: value of optional type 'String?' must be unwrapped to refer to member 'contains' of wrapped base type 'String'
let knownDevTools = danger.github.pullRequest.body.contains("#known")
                                              ^
/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/_tmp_dangerfile.swift:30:47: note: chain the optional using '?' to access member 'contains' only for non-'nil' base values
let knownDevTools = danger.github.pullRequest.body.contains("#known")
                                              ^
                                                  ?
/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/_tmp_dangerfile.swift:30:47: note: force-unwrap using '!' to abort execution if the optional value contains 'nil'
let knownDevTools = danger.github.pullRequest.body.contains("#known")
                                              ^
                                                  !
[31mERROR: Dangerfile eval failed at Dangerfile.swift
[0;0m[31mERROR: Could not get the results JSON file at /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/danger-response.json
[0;0m
```

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 36c50437871f430cb5a7b837308f5b22cafef7b2
</p>

**Comment by ashfurrow** [comment]
Cool this works, I'll cherry-pick the commits onto their own PR to master.
